type_info = [
    ('borough', 'str'),
    ('neighborhood', 'str'),
    ('BuildingClassCategory', 'str'),
    ('TaxClassAtPresent', 'str'),
    ('Block', 'str'),
    ('Lot', 'str'),
    ('EaseMent', 'str'),
    ('BuildingClassAtPresent', 'str'),
    ('Address', 'str'),
    ('ApartmentNumber', 'str'),
    ('ZipCode', 'str'),
    ('ResidentialUnits', 'int'),
    ('CommercialUnits', 'int'),
    ('TotalUnits', 'int'),
    ('LandSquareFeet', 'int'),
    ('GrossSquareFeet', 'int'),
    ('YearBuilt', 'int'),
    ('TaxClassAtTimeOfSale', 'str'),
    ('BuildingClassAtTimeOfSale', 'str'),
    ('SalePrice', 'int'),
    ('SaleDate', 'date'),
    ('bbl', 'str')
]
